name: R Build and Checks
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: R Build and Checks
      uses: e3bo/R-actions@v1.3
      with:
        action: 'build'
        needsBioc: false

